### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by murtyjones** [bhall2001/serverless-nextjs-github-ci-cd#5]
Thanks for this awesome guide!

Any idea how to inject environment variables with this type of a serverless setup? I'm finding it to be surprisingly hard without checking the variables into the repo.

**Comment by fredfgb** [comment]
I think the easiest way to use environment variables in this scenario is to create your secrets in your CICD pipeline, in my case I'm using github actions so you need to reference the secrets and export them as env variables in order to access at build time in nextjs

![image](https://user-images.githubusercontent.com/974311/105992346-c3639e00-6083-11eb-9ef8-414a91205de4.png)

 and in your serverless.yml file you need to reference those variables like this:

![image](https://user-images.githubusercontent.com/974311/105992073-649e2480-6083-11eb-9afe-2beddb568c4f.png)

**Comment by bhall2001** [comment]
Closing. comment above is proper way to handle environment variables.
